balena-io/renovate-config

- .github/renovate.json
- .github/workflows/renovate.yml
- README.md
- repo.yml
> Initial Renovate config and workflow

- .github/renovate.json
> Additional repositories

- .github/renovate.json
> Fix commit message

- .github/renovate.json
> Add preserveSemverRanges to avoid pinning devDependencies

- .github/renovate.json
> Change to use glob expression

- .github/renovate.json
> Preserve global extends

- .github/renovate.json
> Recursively apply config?

- .github/renovate.json
> Correct commit message body

- .github/renovate.json
> Correct commit message

- .github/renovate.json
> Revert extends change

- .github/renovate.json
* https://github.com/product-os/balena-redis-exporter
* https://github.com/product-os/balena-cloudwatch-exporter
> Add repositories

- .github/renovate.json
> Correct auto-merge config

- .github/renovate.json
> Add balena-io-modules/drivelist

- .github/renovate.json
> Add mocha-pod to renovate.json

- .github/renovate.json
> Add Etcher

- .github/renovate.json
- .github/workflows/renovate.yml
> Don't renovate Etcher

- .github/renovate.json
Signed-off-by: Josh Bowling <josh@monarci.com>
> Add more balena-io-modules repos

- .github/renovate.json
> Add support for prometheus/grafana in dockerfiles

- .github/renovate.json
These repos are managed by product-os/renovate-config
> Remove product-os repos

- .github/renovate.json
Signed-off-by: Kyle Harding <kyle@balena.io>
> Add leviathan repositories

- .github/renovate.json
This reverts commit e28820134a8390824ac305c2b4fc5715a12e0ec1.
Signed-off-by: Kyle Harding <kyle@balena.io>
> Revert "Add leviathan repositories"

- .github/renovate.json
- .github/workflows/flowzone.yml
- .github/workflows/renovate.yml
> Use secret instead of env var

- .github/renovate.json
> Add balena-io-modules/balena-env-parsing

- .github/renovate.json
> Add node-ext2fs

- .github/renovate.json
> Revert previous and whitelist commands

- .github/renovate.json
> Revert previous

- .github/renovate.json
> Add balena-sign

- .github/renovate.json
> Enable automerge for digests

- .github/renovate.json
Test setting this unblocks `pr-comment`.
> Disable platformAutomerge

- .github/renovate.json
Simplifies renovate config in tandem with https://github.com/product-os/policies/pull/13
Change-type: minor
> Enable automerge+policy-bot

- .github/renovate.json
> Don't auto-merge unless specified

- .github/renovate.json
> Additional PR labels

- .github/renovate.json
> Add: balena-io-modules/balena-deploy-request

- .github/renovate.json
> depType conditional on newMajor version

- .github/renovate.json
> Correct handlebars logic

- .github/renovate.json
> Try automergeType: pr-comment to delay

- .github/renovate.json
* balena-os/balena-engine (github-release)
* product-os/self-hosted-runners (github-tag => package)
> Add regexManagers

- .github/renovate.json
> One PR in-flight at a time

- .github/renovate.json
- .github/workflows/renovate.yml
Same as https://github.com/product-os/renovate-config/pull/163 (for future proofing)
> Additional Docker registries to source updates

- .github/workflows/renovate.yml
- default.json
- package.json
Set in https://github.com/balena-io/balena-cloud/pull/1153 instead.
> ignorePaths getting ignored

- default.json
> renovate balena-io/analytics-pipeline

- default.json
> renovate arm builder kernels

- package.json
> Set node engine to the required v18

- default.json
> renamed repositories

- default.json
> update sshproxy and process exporter

- default.json
> renovate balena-blog

- .github/workflows/renovate.yml
- default.json
These repositories are now managed in the respective <org>/.github repos.
> Authenticate with installation app token

- default.json
This project has been archived.
> Add compatibility regex for open-balena-base

- default.json
> Enforce strict semver for open-balena-base images

- default.json
See, https://github.com/renovatebot/renovate/issues/4893
> group ssh2 module and types

- default.json
> Use no-review label to conditionally approve via policy-bot

- default.json
> Add balena-builder-worker to renovate

- default.json
https://docs.renovatebot.com/presets-npm/#npmunpublishsafe
> Wait until npm packages are 3 days old

- default.json
> Remove dynamic labels as they are not updated once the PR is open

- default.json
> Set the automerge strategy to merge-commit

- default.json
> Disable semantic commit message prefixes

- .github/workflows/renovate.yml
> Pin renovate image version to 37.27.0

- default.json
> renovate balena-io/logs-to-vector

- default.json
> Enable automerge of lock file maintenance PRs

- default.json
> allow allowPostUpgradeCommand(s)

- default.json
> allow cd shell command

- default.json
> add missing repos

- default.json
> we need to renovate balena-ui

- default.json
> Group npm dependencies with their associated types

- default.json
See: https://balena.zulipchat.com/#narrow/stream/345752-balena-io.2Finternal-tooling/topic/Renovate.20major.20change-types
> Add changelog-entry to the commit footer for the balena-ui repo

- .github/workflows/flowzone.yml
> Remove unsupported Flowzone options

- default.json
See: https://github.com/balena-io-modules/open-balena-base/pull/343
> Remove open-balena-base compatibility workarounds

- default.json
See, https://github.com/renovatebot/renovate/discussions/27280#discussioncomment-8711418
> disable cloning submodules

- default.json
Flowzone expects .github/actions/test/action.yml
as the path for a custom test action and we want those files to be managed as github-actions files.
> Allow custom test actions to be managed by Renovate

- default.json
See: https://balena.zulipchat.com/#narrow/stream/345885-aspect.2Fsecurity/topic/CLI.20Vulnerabilities/near/446083600
> Add balena-cli to managed repositories

- .github/workflows/renovate.yml
Requires:
* https://github.com/balena-io/.github/pull/14
* https://github.com/balena-io/environment-playground/pull/123
* https://github.com/balena-io/environment-staging/pull/3628
* https://github.com/balena-io/environment-staging/pull/3627
* https://github.com/balena-io/environment-production/pull/2456
* https://github.com/balena-io/environment-production/pull/2455
* https://github.com/balena-io/environment-restricted/pull/35
* https://github.com/balena-io/environment-restricted/pull/34
change-type: minor
> Authenticate with AWS to enable Renovation of AMIs and RDS engines

- default.json
See: https://docs.renovatebot.com/modules/manager/pre-commit/
> Enable automated dependency updates for pre-commit
