balena-io/renovate-config

.github/renovate.json

Remove 'v' prefixes from versions so that VB's nested changelogs work

---

.github/renovate.json

This is in an effort to avoid merging a PR that
adds a new field for which we need to write a
migration in the balena-api.
See: https://jel.ly.fish/thread-3605662d-f0c4-4669-bd42-2187a9b919aa
See: https://docs.renovatebot.com/configuration-options/#packagerules

Stop automerging minor bumps of @blalena/open-balena-api

---

repo.yml

* we should change VB's assumption about missing repo.yml == Node project which I don't believe is a safe assumption to make (e.g. this repo doesn't have package.json and doesn't need it)

Replace repo.yml as VB throws up without it

---

.github/renovate.json

Moved to [balena-io-hardware/meta-renovateConfig-sw](https://github.com/balena-io-hardware/meta-renovateConfig-sw) instead.

Remove balena-io-hardware repo

---

.github/renovate.json

This change will trigger Etcher builds for each dependency update, but won't mark the resulting releases final/latest until someone manually checks them and finalises them.

(re)enable Etcher

---

.github/renovate.json

If there is already a v prefix then it is left intact

Avoid adding a v prefix for grafana/prometheus versions

---

.github/renovate.json

https://pre-commit.com/, but [caveat](https://github.com/renovatebot/renovate/blob/main/lib/modules/manager/pre-commit/readme.md)
(e.g. https://github.com/renovatebot/pre-commit-hooks)

Enable pre-commit

---

.github/renovate.json

I am reverting:
```
"automergeType": "pr-comment",
"automergeComment": "LGTM",
```
policy-bot never fires the pr-comment, since the *required* check "policy-bot" is never satisfied. So - a circular dependency pattern.

Revert  automergeType

---

.github/renovate.json

Refactor based on product-os/renovate-config, plus balena-io specifics.
No idea why this still appears in the logs:
```
2023-03-10T00:34:35.5125454Z            {
2023-03-10T00:34:35.5125761Z              "matchPackagePatterns": [".*product-os/self-hosted-runners$"],
2023-03-10T00:34:35.5125898Z              "matchDatasources": ["docker"],
2023-03-10T00:34:35.5126313Z              "versioning": "regex:^((?<prefix>.*)-)?v?(?<major>\\d+)(\\.(?<minor>\\d+))?(\\.(?<patch>\\d+))?(-(?<compatibility>.*))?$"
2023-03-10T00:34:35.5126399Z            }
```

Refactor and update custom versioning

---

default.json

Suspect renovate will struggle to complete with this repo: https://github.com/balena-io/renovate-config/actions/runs/4536510356
We are probably better off isolating this repo to its own renovate-config (balena-io-library/renovate-config), but even then the renovate (dry-run) fails to complete in 3hrs.

renovate balena-io-library/base-images

---

default.json

As of v1.2.8 the self-hosted runner docker tags are following the expected semver-compatibility syntax.

Remove custom versioning for self-hosted runners

---

default.json

We now use policy-bot and labels to determine if a PR can be merged, and auto-merge is enabled automatically by Flowzone.
Having an external service with Administrator access perform merging can result in PRs merging without all required checks.
Change-type: minor

Disable automerge for all update types

---

default.json

Keep the existing update type label so for major
devDependencies we do not auto-approve via policy-bot.

Downgrade devDependencies to change-type: patch

---

default.json

https://github.com/balena-io/sshproxy doesn't have any tests, so this may not be a good idea. Needs second opinion.. or revert if causes problems.

renovate balena-io/sshproxy

---

default.json

See https://docs.renovatebot.com/presets-regexManagers/
Using these regex managers, we can bump ENV and ARG in Dockerfiles and GitHub Actions and Terraform with annotations.
e.g.
```Dockerfile
ARG KUBEDOG_VERSION=v0.5.1
```

Add some convenience regexmanager presets

---

default.json

Renovate labels are not updated when PRs are rebased or change updateTypes, so they cannot be used
as a reliable source of truth.
Change-type: minor

Use renovate automerge instead of custom labels

---

default.json

This allows repos in balena-os to extend balena-io/renovate-config and override the commit message for digests.

Set the commitBody in the digest package rules

---

default.json

In addition to the :automergeStableNonMajor preset, we want to automerge stable minor releases even when the versioning scheme does not support ranges in the format >= 1.0.0.
Specifically, the regex versioning used for open-balena-base does not support version ranges, so instead we need to evaluate as a string.

Automerge stable minor for versions without range support

---

default.json

This will slightly reduce the number of PRs being rate-limited without any notification beyond the dependency dashboard.

Increase concurrent PR limit from 2 to 3

---

default.json

See: https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
Here are the default settings from the [docs](https://docs.renovatebot.com/configuration-options/#lockfilemaintenance)...
```json
{
"enabled": false,
"recreateWhen": "always",
"rebaseStalePrs": true,
"branchTopic": "lock-file-maintenance",
"commitMessageAction": "Lock file maintenance",
"commitMessageTopic": null,
"commitMessageExtra": null,
"schedule": ["before 4am on monday"],
"groupName": null,
"prBodyDefinitions": {"Change": "All locks refreshed"}
}
```

Enable lock file maintenance

---

default.json

See: https://docs.renovatebot.com/presets-default/#automergetypes
See: https://balena.zulipchat.com/#narrow/stream/345752-balena-io.2Finternal-tooling/topic/Renovate.20major.20change-types

Disable automerge of major npm types

---

default.json

In many cases @types are not available at the same as the package so the PR name and branch is misleading.
Just remove the "with types" from the name but
keep the grouping (@types/depName joins depName).
Change-type: minor

Remove "with types" from npm package group name

---

default.json

Renovate expects the "compatibility" field to be a suffix of the semver, not a prefix, so we need workarounds like this to handle the commit body message.

Remove no-systemd-v from open-balena-base updates commit body

---

default.json

See: https://github.com/typicode/husky/releases/tag/v9.0.1
Matches `prepare` script
```json
"node -e \"try { require('husky').install() } catch (e) {if (e.code !== 'MODULE_NOT_FOUND') throw e}\""
```
and replaces it with
```json
"node -e \"try { (await import('husky')).default() } catch (e) { if (e.code !== 'ERR_MODULE_NOT_FOUND') throw e }\" --input-type module"
```
on `major` updates to the `husky` package
also removes these lines from `.husky/pre-commit`
```shell
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
```
... and fortunately for us, major updates are configured to not automerge so we will catch any errors in this process

Patch prepare script on husky major updates

---

.husky/pre-commit
commands/husky-v9-patch.js
default.json
package.json
updatePackageRules.js

Allow the use of a fully-formatted node.js scripts
for postUpgradeTasks by automatically encoding them
and updating default.json in pre-commit.

Fix husky postUpgradeTasks to use base64-encoded script

---

default.json

Rather than creating a single PR to hop from 10.x to 12.x, there will be separate PRs created for 11.x and 12.x so we can choose which to merge.
See: https://docs.renovatebot.com/presets-default/#separatemultiplemajorreleases

Separate each major version of dependencies

---

default.json

Disable automerge to avoid breaking changes introduced on arbitrary dates.

Use custom versioning for Minio

---

default.json

We want to avoid the minio client being bumped when the server is incompatible or held back.

Group minio client and server dependency bumps

---

default.json

This is primarily to reduce the number of active PRs and test runs.

Group GitHub Actions patch and digest updates together
